version: '2'
services:
    seuaa-mysql:
        container_name: seuaa-mysql
        image: mysql:5.7.14
        # volumes:
        #     - ~/volumes/jhipster/seuaa/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=seuaa
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
